[package]
name = "elysian-core"
version = "0.1.0"
edition = "2021"

[features]
default = []
internal = []

[dependencies]
rust-gpu-bridge = { path = "../../../bevy-rust-gpu-project/crates/rust-gpu-bridge", features = ["glam"] }

uuid = { version = "1.4.0", features = ["v4"] }
