[package]
name = "elysian-shapes"
version = "0.1.0"
edition = "2021"

[dependencies]
elysian-core = { path = "../elysian-core", features = ["internal"] }
elysian-macros = { path = "../elysian-macros" }
indexmap = "2.0.0"
linkme = "0.3.13"
