[package]
name = "test-mesh"
version = "0.1.0"
edition = "2021"

[dependencies]
elysian = { path = "../../" }
test-shapes = { path = "../test-shapes" }

image = "0.24.7"
imageproc = "0.23.0"
viuer = "0.6.2"
