[package]
name = "elysian-interpreter"
version = "0.1.0"
edition = "2021"

[features]
default = []
print = []

[dependencies]
elysian-core = { path = "../elysian-core" }
rust-gpu-bridge = { path = "../../../bevy-rust-gpu-project/crates/rust-gpu-bridge" }
tracing = "0.1.37"
