[package]
name = "elysian-interpreter"
version = "0.1.0"
edition = "2021"

[features]
default = []
print = []

[dependencies]
elysian-core = { path = "../elysian-core" }
elysian-ir = { path = "../elysian-ir" }
elysian-math = { path = "../elysian-math" }
tracing = "0.1.37"
