[package]
name = "test-rhai"
version = "0.1.0"
edition = "2021"

[dependencies]
rhai = { version = "1.16.1", features = ["no_closure", "internals", "sync", "bin-features"] }
rustyline = "12.0.0"
glam = "0.24.1"
image = "0.24.7"
viuer = "0.6.2"
rayon = "1.8.0"
