[package]
name = "elysian-math"
version = "0.5.0"
edition = "2021"

[features]
default = ["glam"]
glam = ["dep:glam"]
spirv-std = ["dep:spirv-std"]

[dependencies]
glam = { version = "0.24.0", optional = true }
spirv-std = { version = "0.9.0", optional = true }
